resolve base64 version conflict
Deploy fails with Phusion Passenger logging this error:
```
error: You have already activated
base64 0.1.1, but your Gemfile requires base64 0.2.0.
```

In Ruby 3.2.x, the default base64 gem is 0.1.1. In 3.3.x, it's 0.2.0.

To avoid a mismatch, this changes the Gemfile.lock to use `0.1.1`.