fix: undefined method `secrets` error
rails update fails with:
```
NoMethodError: undefined method `secrets' for #<Z::Application> (NoMethodError)

  config.dsn = Rails.application.secrets.sentry_dsn
                                ^^^^^^^^
```

Change to use .env instead